spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.102.143.2:3306/oacenter?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=UTC
    username: java
    password: 123456
mybatis-plus:
  mapper-locations: classpath:xml/*.xml


